function DiscreteTransferMatrixJacobian = EKF_TransferFcnJacobian(in1)
%EKF_TRANSFERFCNJACOBIAN
%    DISCRETETRANSFERMATRIXJACOBIAN = EKF_TRANSFERFCNJACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Feb-2019 11:22:43

d_delta = in1(2,:);
delta = in1(1,:);
v = in1(3,:);
DiscreteTransferMatrixJacobian = reshape([1.0,1.964e-1,0.0,0.0,0.0,0.0,0.0,2.0e-2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,v.^2.*-1.818181818181818e-2,1.0,0.0,0.0,0.0,0.0,0.0,v.*-8.0e-3,2.0e-2,1.0,0.0,0.0,0.0,0.0,d_delta.*-8.0e-3-delta.*v.*3.636363636363636e-2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0e-2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.6e-3,0.0,1.0],[7,7]);
