function DiscreteTransferMatrix = EKF_TransferFcn(in1)
%EKF_TRANSFERFCN
%    DISCRETETRANSFERMATRIX = EKF_TRANSFERFCN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Feb-2019 11:22:43

T = in1(7,:);
d_delta = in1(4,:);
d_theta = in1(2,:);
dd_delta = in1(6,:);
delta = in1(3,:);
theta = in1(1,:);
v = in1(5,:);
DiscreteTransferMatrix = [d_theta.*2.0e-2+theta;d_theta+theta.*1.964e-1-d_delta.*v.*8.0e-3-delta.*v.^2.*1.818181818181818e-2;d_delta.*2.0e-2+delta;d_delta+dd_delta.*2.0e-2;T.*1.6e-3+v;dd_delta;T];
