function C = measurementFunctionFile(theta,d_theta,delta,d_delta,v)
%MEASUREMENTFUNCTIONFILE
%    C = MEASUREMENTFUNCTIONFILE(THETA,D_THETA,DELTA,D_DELTA,V)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 10:21:27

C = [theta;d_theta;delta;d_delta;v];
