function x_n1 = stateTransitionFile(theta,d_theta,delta,d_delta,v,dd_delta,T)
%STATETRANSITIONFILE
%    X_N1 = STATETRANSITIONFILE(THETA,D_THETA,DELTA,D_DELTA,V,DD_DELTA,T)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 10:21:27

x_n1 = [d_theta./5.0e1+theta;d_theta+theta.*1.964e-1-(d_delta.*v)./1.25e2-(delta.*v.^2)./5.5e1;d_delta./5.0e1+delta;d_delta+dd_delta./5.0e1;T./6.25e2+v];
